/* ============================================================
   scripts/test.js — the Truth Layer (one command, one verdict)

   Run:  npm test    (or)   node scripts/test.js

   The council's arbiter. Every agent — Claude, Codex, or a human — must leave
   this GREEN. It (1) syntax-checks every source file, then (2) runs every test
   suite. Any failure → non-zero exit, so CI and pre-commit hooks catch it.

   No DB, no AI key required — everything here is pure/deterministic on purpose,
   so the truth layer is fast, hermetic, and reproducible anywhere.
   ============================================================ */

const { execFileSync } = require('child_process');
const fs   = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');

let failed = 0;
const step = (label, fn) => {
  process.stdout.write(`\n▶ ${label}\n`);
  try { fn(); } catch (e) {
    failed++;
    if (e.stdout) process.stdout.write(String(e.stdout));
    console.log('  ✗', (e.message || 'failed').split('\n')[0]);
  }
};

// 1 ── syntax: every source file parses (catches a broken commit instantly) ──
step('syntax — node --check all sources', () => {
  const files = [];
  const addDir = d => { try { fs.readdirSync(path.join(root, d)).forEach(f => { if (f.endsWith('.js')) files.push(path.join(d, f)); }); } catch (_) {} };
  ['ai', 'scripts', 'js'].forEach(addDir);
  ['server.js', 'db.js'].forEach(f => { if (fs.existsSync(path.join(root, f))) files.push(f); });
  for (const f of files) execFileSync('node', ['--check', path.join(root, f)]);
  console.log(`  ✓ ${files.length} files parse`);
});

// 2 ── suites: each exits non-zero on failure ───────────────────────────────
const SUITES = [
  'baseline-smoke.js',
  'intelligence-smoke.js',
  'privacy-smoke.js',
  'person-model-smoke.js',
  'eval.js',
  'invariants.js',
  'packs-language-smoke.js', // domain LANGUAGE pass: org-voice directives, role-sensitivity, audit
  'domain-cleanup-smoke.js', // one language source: no legacy vertical prose; role ladder invents no titles
  'evidence-smoke.js',     // the canonical evidence envelope: normalise/validate/dedupe/promote
  'identity-reresolve-smoke.js', // the identity lifecycle: held-back evidence resolves + promotes once
  'mapping-smoke.js',            // the mapping contract: fingerprint/drift/transform/gate (pure)
  'mapping-lifecycle-smoke.js',  // the mapping approval lifecycle end to end (hold→approve→activate→reprocess)
  'sync-smoke.js',               // sync reliability primitives (pure): classify/backoff/rate-limit/health/staleness
  'sync-reliability-smoke.js',   // sync reliability invariants: idempotent replay, correction, deletion, concurrency
  'policy-smoke.js',             // the organisational constitution: what the assistant may DO (pure)
  'action-smoke.js',             // the universal action contract: recommend→…→learn stage machine (pure)
  'reasoning-smoke.js',          // the three reasoning boundaries: pre-kernel/kernel/post-kernel (pure)
  'workspace-smoke.js',          // the unified workspace item model: typed, scoped, deterministic privacy (pure)
  'reasoning-boundaries-smoke.js', // the 10 architectural invariants, end to end
  'private-evidence-smoke.js',   // the 18 private-canonical-evidence invariants (owner-only, purpose-scoped)
  'workspace-experience-smoke.js', // MyWorkspace experience boundaries (today/ask/lenses via the gateway)
  'adapters-smoke.js',           // capability → canonical evidence adapters (pure)
  'legacy-convergence-smoke.js', // legacy paths converge on canonical evidence (check-in/backfill/context)
  'advisor-migration-smoke.js',  // the member advisor on canonical evidence + kernel + post-kernel (privacy-critical)
  'checkin-migration-smoke.js',  // the daily check-in: canonical-only intelligence, kernel trends, self-feed protection
  'checkin-hardening-smoke.js',  // post-migration watch-items: frozen signal, reconciliation, classification audit, intervention edges
  'workspace-assessment-smoke.js', // assigned work → canonical evidence: commitment/submission/revision/complete Assessment (live)
  'assessment-consumption-smoke.js', // the unified assistant consumes the complete Assessment (scale-aware, journey-aware, no double-count)
  'scenario-convergence-smoke.js', // scenario/memberResults converge onto the same canonical assessment model; legacy value-signal cutover
  'assessment-presentation-smoke.js', // server-supplied assessment presentation state; frontend no longer judges a raw score
  'assistant-runtime-smoke.js',    // unified MyWorkspace assistant runtime: one composer, bounded turn, confirmable proposals
  'assistant-interface-smoke.js',  // unified MyWorkspace INTERFACE: one composer/identity, lenses as bounded hints, confirmable proposal cards
  'proactive-smoke.js',            // the proactive surfacing layer: post-kernel ProactiveInsight projection, surfacing policy, audience safety, bounded preferences
  'governance-smoke.js',           // architectural gravity: proactive DELIVERY lives ONLY in ai/behaviour.js; every surface consumes one pipeline
  'retrieval-smoke.js',            // grounded retrieval over canonical evidence: authorised-before-composition, cited, no-key extractive, full privacy/integrity matrix
  'intake-smoke.js',               // universal evidence intake: one governed ingestion boundary (text/md/pdf/docx/csv/json) → canonical evidence → grounded retrieval; dedup/supersede/delete, provenance, privacy
  'capture-smoke.js',      // capture-intent detection (pure): explicit save-commands vs one-tap offers vs questions — detection automatic, persistence deliberate
  'turn-grounding-smoke.js', // the grounded conversational turn: /api/assistant/turn answers from authorised evidence via the ONE _assistantAnswer boundary; full leak matrix + mixed-turn ordering + capture unchanged
  'org-state-smoke.js',    // organisational-state projection (pure): objectives/events/decisions/requirements over admissible evidence + config + packs; ordered ownership, deterministic impact/urgency, claim states, readiness, provenance; drives uncertainty generation
  'org-context-smoke.js',  // operating-context intake (pure): conversational extraction → proposed records, validation hard-blocks/warnings, dependency-cycle detection, authority-by-confirmer, projection with supersession — extraction automatic, persistence deliberate
  'org-context-http-smoke.js', // operating-context governed flow + scenarios (HTTP): preview→confirm→state→uncertainty, member-unverified, tenant isolation, supersession/history, import validation, private refused, cache invalidation
  'readiness-smoke.js',    // team-readiness view-model projection (pure): deterministic focus, semantic states (no percentage), structural non-blaming statements, routed questions, disputed preserved, calm empty states
  'readiness-http-smoke.js', // team-readiness + role-binding (HTTP): confirmed context→grounded briefing, missing→routed question, bind/rebind/history, private never influences, tenant isolation, fingerprint invalidation, leader-only
  'resolve-loop-smoke.js', // grounded answer-and-confirm loop (HTTP): uncertainty→answer→adjudicate→preview→confirm→governed write→re-derived readiness; authority-by-ownership, vague≠satisfied, disputed preserved, non-answer/ambiguity, idempotent, no projection mutation
  'org-memory-smoke.js',   // organisational memory (pure): the versioned, EXPLAINABLE derived-state timeline — deterministic fingerprinted snapshots + dedup on observable change; trigger provenance (normalised/redacted); semantic-version gating (incompatible → neutral rebaseline, never false transitions); diffs classify a user-facing direction AND a deterministic cause; removals keep a structural reason; leader-safe explain (history, not learning)
  'org-memory-http-smoke.js', // organisational memory (HTTP): governed writes stamp server-derived triggers (context/resolution/role-binding); client cannot inject a trigger; "what changed" + cause; explain endpoint (leader-only, tenant-isolated, no id/hash/version leaks); legacy snapshots restore without fabricated provenance → rebaseline; private/wellbeing never enters; durable store
  'org-learning-smoke.js', // learning engine Phase B1 (pure): compatible-only intervals (rebaseline/legacy excluded, tenant-guarded, malformed-safe); deterministic observation taxonomy (repeated transition/cause, coded sequence, recurring requirement, non-causal readiness co-occurrence, stable non-change); dedup + stable identity + supersession-ready fingerprints; contradictions/limitations retained; redacted, non-causal public output (history, not recommendations)
  'org-learning-http-smoke.js', // learning engine Phase B1 (HTTP): direct evidence capture stamps evidence_recorded (not temporal); client cannot inject a trigger; observations derive from own memory, leader-only + tenant-isolated + redacted + non-causal; dismissal affects only the artifact + never resurfaces; materially-new support reappears; durable store
  'org-playbook-smoke.js', // learning engine Phase B2 (pure): counter-evidence (for/against), qualitative confidence bands (never a number), candidate eligibility (repeatable ways-of-operating only), governed candidate → playbook-entry shaping (module never endorses/writes), deterministic dedup/order, redacted non-causal public output
  'org-playbook-http-smoke.js', // learning engine Phase B2 (HTTP): candidates derived from own observations + weighed; the engine never writes the playbook — only a leader confirm does; confirm/dismiss governed + idempotent + injection-resistant; leader-only, tenant-isolated, redacted; confirming never mutates memory; durable store
  'org-graph-smoke.js',    // organisational information-web scoping (pure): asymmetric visibility — a parent sees its whole subtree, a child sees only its direct parent(s); multi-parent honoured; routing walks up to the nearest leader; cycle-safe + deterministic
  'org-graph-http-smoke.js', // information-web scoping wired into org-state (integration): node-scoped evidence flows UP to parent leaders + the top but never across to a sibling branch; a member sees their own node; an org with NO node structure is unchanged (org-wide)
  'conversation-smoke.js', // grounded conversation engine + member projection (pure): required claims from a definition, grounded classification (already-known skips, stale refreshes, vague never resolves), next-question selection, adjudication composed with the EXISTING adjudicateAnswer (member reported / owner authoritative / vague → corroboration), governed proposals (never a projection mutation), completion; plus interpretation-over-score projection with placeholder/duplicate-feedback detection
  'conversation-http-smoke.js', // grounded assessment intake (HTTP): start → answer → preview (no write) → confirm (canonical evidence) → re-derive → next/complete; vague never resolves; nothing written before confirm; ownership server-derived (another member refused); resume re-derives + skips already-known; abandon writes nothing; MyWorkspace projection leads with meaning + never shows placeholder feedback as individual
  'assistant-chat-http-smoke.js', // THE CHAT ACTUALLY WORKS (HTTP): an org/team question is never met with a bare "not enough authorised evidence" dead end when the reasoner has a read (outstanding / who needs support / are we ready / tell me about the org all answer from the grounded read); a greeting gets a warm human reply; a PURE question is never met with "save as note / log a check-in" cards, while a genuine disclosure still offers the check-in; an off-topic knowledge question is still answered honestly (never fabricated).
  'assistant-team-status-http-smoke.js', // "HOW'S THE TEAM DOING?" (HTTP): the conversational assistant answers a team-status question from the REASONER's already-scoped read (the same grounded picture the Today voice shows) instead of the old "not enough authorised evidence" dead end; a compound "feeling down, how's the team?" still offers the personal check-in AND answers the team question; leak-safe across branches.
  'metrics-smoke.js', // METRICS (pure): per-org usage counters accumulate, snapshot ranks busiest-first with a per-event breakdown, can be scoped to one org (a superadmin's own view, no cross-org leak), and a null org never crashes.
  'errorlog-smoke.js', // ERROR LOG (pure): redacting ring buffer — records route/method/status, keeps most-recent-first, caps size, and REDACTS PII/secrets (emails, bearer tokens, api keys) + truncates stacks, so an error report can never itself leak.
  'observability-http-smoke.js', // OBSERVABILITY (HTTP): a captured error is visible to a superadmin (redacted) and refused to everyone else (403) — pilot visibility without leaking PII.
  'prompt-injection-smoke.js', // PROMPT-INJECTION RESISTANCE (pure): governance is enforced in CODE — a jailbroken model output can't leak or fabricate org facts; uncited/forged-citation org claims are demoted to questions (never asserted), a legit cited claim still works, and an injected fabricated figure never reaches a rendered artifact.
  'cross-org-isolation-http-smoke.js', // CROSS-ORG ISOLATION (HTTP): the write endpoints that once trusted a body-supplied orgCode/authorId now take identity ONLY from the session — a user in org A can't write into org B, forge another person's identity, invite themselves in as an admin, or edit/escalate another user; unauthenticated writes are 401; legitimate self-writes still work (not over-locked).
  'rate-limit-smoke.js', // RATE LIMIT (pure): fixed-window limiter allows up to the limit then blocks, resets after the window, reset() clears a key (successful login), sweep() prunes stale windows.
  'abuse-controls-http-smoke.js', // ABUSE & COST CONTROLS (HTTP): repeated bad logins lock out (429) and a correct password clears the counter; lockout is per email+IP (a clean IP still works); the per-org LLM budget never green-lights a call when the engine is off (safe default) — over-budget degrades the same way.
  'gateway-smoke.js', // THE GATEWAY (pure): the request we build is one the configured model will accept — sampling parameters are sent only to models that still take them (Sonnet 5 and every newer model 400 on `temperature`, which failed the composer and the intake on every turn), an unrecognised model errs toward no sampling, the fallback floor is a constant so pointing both tiers at one model cannot disable the downshift, and a sampling rejection retries rather than killing the turn.
  'reach-smoke.js', // REACHING THE RIGHT PERSON (HTTP, model OFF): an org names who handles what, a matter is offered to the person whose remit covers it (injury to medical, leadership to performance), ordinary talk offers nobody, nothing moves until the member confirms, their EDIT is what gets shared, a share aimed at one person reaches exactly that person and no other member or staff, a proposal executes at most once, and an org that has named nobody offers nobody rather than inventing a role.
  'safeguarding-smoke.js', // SAFEGUARDING (pure): deterministic distress detection (crisis vs concern vs none, LLM-independent), errs toward sensitivity, never false-flags ordinary performance talk; a crisis response is transparent that a safe adult is being told and carries real crisis resources; resources are overridable per org.
  'safeguarding-http-smoke.js', // SAFEGUARDING (HTTP, model OFF): a crisis short-circuits the turn (mode:safeguarding, no reasoning/no note card) into a warm response with real resources; a flag routes to the safeguarding lead; only the lead can see/resolve the queue; ordinary football talk is untouched; crisis resources are always readable so help is never gated.
  'library-migration-smoke.js', // LEGACY NOTES → LIBRARY MIGRATION: the one-home sweep turns existing notes into Library note-items with the right owner + visibility ('shared'→shared, 'private'/'anonymous'→private, never re-exposed), preserves created time, leaves orgNotes intact, is idempotent (re-run adds nothing), and a note made via the legacy /api/notes endpoint also mirrors into the Library.
  'library-http-smoke.js', // THE LIBRARY (HTTP): personal folders holding items (notes, saved chats, artifacts), private by default and shareable by explicit choice; a note files into a folder; the chat→library bridge snapshots only MY conversations; PRIVATE is owner-only while SHARED is visible to teammates (visibility, never a silent belief); only the owner can edit/move/delete; deleting a folder unfiles its items (never deletes them).
  'assistant-history-http-smoke.js', // PRIVATE CHAT HISTORY + MULTI-TURN MEMORY (HTTP): turns thread into a conversation (returns a conversationId); a follow-up on the same id continues the thread (memory fed back to the reasoner); threads are listable + readable with the provenance channel; SELF-ONLY (one user can't read or delete another's history); the owner can delete their own thread (private & permanent until then); no id opens a fresh thread. None of it becomes org data.
  'render-artifact-smoke.js', // GOVERNED RENDER/PRESENT (pure): the LLM-as-output-interface may style/narrate ONLY the dataset it was given; EVERY figure in the output must trace to the source data — an invented number is caught (no artifact returned) so a fabricated figure never reaches the reader; a fabricated row ref is dropped; a deterministic factual draft (summary + email) works with no model; an empty dataset says "nothing recorded", never a fabricated report.
  'render-artifact-http-smoke.js', // GOVERNED RENDER/PRESENT (HTTP): POST /api/artifact/render returns a confirm-gated DRAFT (delivered:false — nothing sent, outbound stays policy-gated) composed from the reader's own scoped grounded data (leak-safe across branches); with no model it degrades to a truthful plain draft from the recorded read; an unsupported format falls back to summary (no crash).
  'kernel-coreasoning-smoke.js', // KERNEL CO-REASONING (pure): the LLM helps the brain reason about WHAT TO LOOK AT, never who — the digest it sees is de-identified (counts + structure, no person); a hypothesis is always tagged a hypothesis at 'unconfirmed' readiness and is NEVER a belief; any suggestion leaking a person's name is dropped; a framing survives only on an already-confirmed pattern; the prompt bars naming individuals and predicting outcomes.
  'kernel-coreasoning-http-smoke.js', // KERNEL CO-REASONING (HTTP): the surface returns a de-identified aggregate picture (counts + structure) that names no individual though the ledger is full of named beliefs; with no model it degrades honestly (aggregates always present, hypotheses need the engine, never fabricated); insights/admin-gated (a plain member gets 403).
  'reasoning-register-smoke.js', // TWO-REGISTER GOVERNED REASONING (pure): the classifier separates org_fact / world_knowledge / mixed / planning questions (the structured replacement for regex whack-a-mole); the assembler enforces CITE-OR-ASK in code — an org_data claim with no authorised citation is demoted to a question (never asserted), general knowledge is kept but labelled, a user's unverified assertion becomes a confirmation-gated capture; the system prompt forbids inventing org facts.
  'reasoning-edge-http-smoke.js', // THE GOVERNED REASONING EDGE (HTTP): a world-knowledge/planning question ("why is a 4-3-3 better than a 5-3-2?", "help me build a session") is treated as a REASONING question, not forced through org-truth retrieval and dead-ended; with no model it degrades honestly (says it needs the engine, never fabricates); an org-fact question stays the deterministic grounded read (no egress); the qa contract carries the provenance channel.
  'assistant-assessment-http-smoke.js', // ASSESSMENT REQUEST (HTTP): a member asking for an assessment ("I'd like a short assessment to help me improve at time management", "make the assessment together", "assess me on my defending") is recognised as an assessment request — acknowledged topic-aware, offered an assessment_start action, capture/note card suppressed — instead of defaulting to "save as a private reflection"; an ordinary disclosure is not false-flagged as an assessment.
  'intake-wired-http-smoke.js', // THE EARS, WIRED (HTTP): ai/diagnose.js is the kernel, this pins the wiring. Intake never blocks the reply (it runs after the turn, improving the NEXT answer rather than delaying this one); what it builds is a WORKING PICTURE, never evidence and never a belief; /api/inquiry is strictly self-scoped (another member sees none of it, unauthenticated is 401) and exposes an unconfirmed hypothesis with a DETERMINISTIC confidence band and its rival explanations rather than a bare verdict; and with no model configured the turn is completely unaffected.
  'diagnose-smoke.js',     // SEMANTIC INTAKE (pure): the input side of the flip. The old ears were a ~40-stem lexicon that turned "struggling with my first touch when someone closes me down" into support_need=true, starving everything downstream. Pins the guarantees that make an intelligent intake layer SAFE: the model may propose but never CONCLUDE and never assert its own confidence; every observation carries a span quoted verbatim from what was actually said, and every interpretation/hypothesis rests on one; the four epistemic levels never collapse; confidence is computed deterministically from independence, directness, authority, corroboration, recency, specificity and contradictions; a turn is scored on what it was worth, with repetition, unsupported inference and PREMATURE CERTAINTY punished so the metric cannot be gamed by getting cocky; and the kernel ranks what to learn while the model only phrases it.
  'composer-smoke.js',     // THE COMPOSER (pure): the flip — the model writes the reply and the deterministic core RETRIEVES the authorised material and VERIFIES what came back. Pins THE CAGE: general/world reasoning passes untouched (it is labelled, not fact-checked), but an invented ORGANISATIONAL specific — a teammate's name, a quoted item title, a count claimed about their records — is refused so the caller degrades honestly instead of shipping a fabrication. Also pins that the context block carries the DOMAIN (so "finishing" for a footballer is not read as finishing tasks) and that an empty bundle states its own absence.
  'assistant-voice-recall-http-smoke.js', // RECALL + SELF-VOICE + CLARIFIER OVERRIDE: "what did I just tell you?" is its own register, answered deterministically from the conversation thread (no model, no egress, cannot fabricate) instead of dead-ending on the evidence store; a belief whose subject is the READER is rendered second-person ("you've eased off"), never the leader-facing third person ("Ashton Mbeki has been pulling back") said to Ashton; an explicit assessment request leads over the ambiguous assigned-work clarifier; and confirm always returns a human sentence, never a raw actionType.
  'assistant-answer-hijack-http-smoke.js', // THE DETERMINISTIC HIJACK + ASSESSMENT CONFIRM (HTTP): the reasoner's STANDING read (the attention digest) is marked and never counts as an answer to what was asked — so unmatched questions stop returning the same canned "here's what deserves your attention" text and the governed reasoner gets the question; an explicit assessment request LEADS the reply (not buried behind an unrelated "which one do you mean?" clarifier) while a status-style mention is not false-flagged; and confirming assessment_start works (it used to 400 "unknown proposal type"), creating a real self-assigned assessment.
  'member-chat-threading-http-smoke.js', // MEMBER CHAT THREADING (HTTP): Fix 2 step 1 — a member's plain chat threads into ONE saved conversation across turns (same runtime/endpoints as the leader), retrievable from their own history, self-only (another member gets 403/404); a work-item/member-support turn stays a scoped one-off, so the personal thread isn't polluted.
  'assistant-person-read-http-smoke.js', // PERSON-SCOPED READ + PATTERNS + SUMMARISE (HTTP): "pull up X's profile" / "how is X doing" answers from what the reasoner holds about that named person (closing the inconsistency where the overview named someone but a direct ask dead-ended), leak-safe (a leader outside their area is declined, never shown the read), never a fabricated dossier; an imperative info-request routes to the answer path (not a capture card); "what patterns have you learnt" surfaces the consolidated cross-person reads (distinct content, no repeat); "summarise the org / make sense of the data" reaches the grounded read instead of "not enough authorised evidence".
  'org-answer-smoke.js',   // scoped organisational answering (pure): explicit intent detection, grounded answers composed from the scoped org-state's own claims (never invented), honest limitations, owner-routing when unanswerable, member-safe output (no ids/authority)
  'org-answer-http-smoke.js', // scoped organisational answering (HTTP): the SAME question is answered per branch of the information web — a child's shared item is "recorded" for its parent but still "outstanding" for a sibling lead (no cross-branch leak); members answered in-scope; unanswerable → routes to a lead; node-less org answers org-wide
  'org-routing-smoke.js',  // node-aware routing (pure): unresolved work routes to an EXPLICIT owner (never inferred from ancestry), escalates to the nearest leader when unowned, flags multi-parent-with-no-owner as a conflict (surfaced to all, decided by a human), dedupes multi-path recipients, rolls audience-safe summaries UP a leader's own subtree (sibling branches never included)
  'org-routing-http-smoke.js', // node-aware routing (HTTP): a resolved owner gets the item in their inbox + subtree rollup; a sibling branch lead never sees it (no leak); the top leader's rollup spans the org; conflicts scoped to recipients; node-less org returns a valid empty view
  'reason-smoke.js',       // the Reasoner / belief ledger (pure): the layer ABOVE the snapshot detector — observations accumulate into hypotheses held provisionally; confidence is evidence-volume net of counter-evidence; a same-axis progress signal CONTESTS the matching risk belief; silence lets a belief go dormant; the same risk across people in a scope becomes ONE shared hypothesis; register (support/scout/acknowledge) encodes "a time and a place"; every proposal is proposal-gated (surface, never act); claims never leak a score/quote; deterministic + dedupes + persists across ticks
  'reason-http-smoke.js',  // the Reasoner over HTTP (governed boundary): GET /api/reason/agenda is leader-gated; the ORG-WIDE belief ledger is read SCOPED per leader (a belief about a person routes only to leaders who may see them; a sibling branch lead never sees it — no leak); ripe beliefs carry proposal-gated next steps; the projection leaks no evidence basis / support records / node scope; deterministic; ledger persisted; feedback closes the loop (leader-gated + subject-contest); the brief speaks the deterministic voice with no AI
  'reason-heartbeat-http-smoke.js', // THE BRAIN DOES NOT SLEEP (HTTP): a background sweep (_reasonSweep) reasons over every org with NO leader present, so a belief is already waiting the first time anyone looks; and an event nudge — wired into the real note-share endpoint — drops the stale tick cache so the next read re-reasons with the new input instead of serving a pre-note belief state. Reasoning no longer depends on someone happening to open the app.
  'reason-ambient-http-smoke.js', // AMBIENT SENSING (HTTP): reason-on-event is no longer limited to a shared note — ANY new signal reaching the kernel (here a member syncing their calendar) nudges the reasoner, so the next read re-reasons with the new reality instead of a stale pre-signal state. The brain stays awake between heartbeats.
  'reason-input-http-smoke.js', // LANGUAGE becomes reasoner signal (HTTP): a member's SHARED notes, read deterministically by ai/comprehend (no model), accumulate into a support-first belief the leader sees — while their PRIVATE and SENSITIVE notes never feed the org reasoner and never leak. Proves the input-richness wiring end to end.
  'understanding-smoke.js', // the INPUT translator's safety core (pure): an untrusted LLM classification is FORCED through an allow-list — output carries no raw text/quote/protected trait and nothing off the theme list; sentiment/intensity clamped; smuggled traits fail safe; one note → one tentative low-severity observation (accumulation does the rest)
  'notes-smoke.js',        // pinned + team-shared notes governance (pure): private by default; sharing is refused for a privacy-sensitive note even if the author asks; pin/share are reversible pure patches; the team-view leaks no sensitivity / private AI reply / internal id; shelf orders pins first
  'notes-http-smoke.js',   // pinned + team-shared notes (HTTP): the author shares/pins; the privacy gate hard-blocks sharing a sensitive note; a shared+pinned note reaches teammates IN SCOPE (a sibling branch never sees it — no leak) via the safe projection; pinning needs visibility; un-sharing takes team visibility back; grounded ask is visibility-gated + note-only
  'self-model-smoke.js',   // the SELF-MODEL (pure): the reasoner pointed at its OPERATOR — only an allow-listed set is learnable (surveillance ignored); confidence is DISTINCT DAYS (a habit, not a one-off); an established habit becomes a proposal-gated accommodation; accept applies + stops proposing, dismiss briefly, reject long; dormant when it stops; full transparency
  'self-model-http-smoke.js', // the SELF-MODEL (HTTP): observing learns only allow-listed patterns; an established habit surfaces as a proposal-gated accommodation; accept returns the setting + stops proposing; reject stands it down; feedback validated; a self-model is PRIVATE — another user never sees it
  'report-smoke.js',       // the grounded ARTIFACT layer (pure): renders truth, never manufactures it — a fact with no source is DROPPED (never printed); an empty section says so honestly; deterministic; the HTML is self-contained, escapes content, carries the honesty footer
  'report-http-smoke.js',  // the grounded report (HTTP): GET /api/report/team assembles a real print-ready report from the reasoner + confirmed playbook, every line showing its source, with the honesty footer; leader-gated (a member is refused and gets no team content)
  'brief-smoke.js',        // the node-aware BRIEF composer (pure): composes, never reasons — leader vs member get different shapes + offer sets; every offer is allow-listed + proposal-gated; items come only from the reads given (never fabricated); an offer appears only when its input is present; empty inputs → an honest steady brief; deterministic
  'brief-http-smoke.js',   // the node-aware BRIEF (HTTP): the web does its four jobs — LEVEL (node leader → leader brief, member → member brief), SCOPE (a leader's reads are their own branch; a sibling's person never appears — leak-safe both ways), ROUTE (a member is pointed at a real leader who can help); every offer proposal-gated; greets by name + time of day
  'language-guard-smoke.js', // the NO-PREDICTION / NO-DIAGNOSIS guard (pure): the rule the system lives by, enforced at every LLM edge — predictive/forecasting/diagnostic phrasings are caught (→ caller falls back to the deterministic line), while the system's OWN descriptive outputs (reasoner/brief/report) all pass
  'voice-smoke.js',        // IntelliQ's OWN voice (pure): the assistant speaks warmly WITHOUT an LLM — openings compose from the given facts, invent nothing, are deterministic with stable variety, and NONE of them (252 generated) ever predicts or diagnoses. The LLM is out of the assistant's mouth.
  'comprehend-smoke.js',   // deterministic UNDERSTANDING (pure): the assistant reads free text into bounded features (sentiment + allow-listed themes) WITHOUT an LLM — negation-aware ("not tired" ≠ tired), invents nothing, never extracts a clinical/protected word as a theme, deterministic, and flows through the understanding guard into a reasoner observation. The LLM is out of the ears too.
  'no-egress-smoke.js',    // DETERMINISTIC-ONLY / NO-EGRESS mode: the long-term guarantee — even with a key configured, no-egress makes every LLM edge go dark (enabled()/canUnderstand() false), complete() hard-refuses, and the env form (IQ_DETERMINISTIC_ONLY) can't be re-enabled at runtime. An org can PROVE nothing about their people leaves the box.
  'kernel-travels-http-smoke.js', // THE KERNEL TRAVELS (HTTP): a SCHOOL org runs the exact same stack a club does — the reasoner reads a student's shared notes into a support-first belief the teacher sees, privacy still keeps a private note out, and the access is still recorded in the accountability trail — with the ONLY difference being the display vocabulary (student/class/lesson). Proves IntelliQ is an industry-agnostic engine: same kernel + governance, only the words change.
  'delivery-smoke.js',     // outbound DELIVERY (pure): the last mile holds the line — a care-flagged/sensitive read is NEVER eligible to leave the box; an empty digest is never sent; quiet hours + a once-per-day cap stop spam; opt-in is required; the digest/alert are composed only from the reads given (nothing invented); an alert fires only for something genuinely worth interrupting; deterministic
  'delivery-http-smoke.js', // outbound DELIVERY (HTTP): opt-in → subscribe → preview → test end to end; the preview shows exactly what would leave the box with any care-flagged read EXCLUDED; a test send is composed + audit-logged (outbound_delivery, content-free); consent required; an org in NO-EGRESS mode refuses to subscribe/send and the sweep delivers nothing
  'audit-smoke.js',        // the ACCOUNTABILITY TRAIL (pure): an append-only, content-free, tamper-evident record of who accessed whose data — only allow-listed actions; each entry hash-chains to the prior so any edit or deletion is detectable; a subject trail shows who accessed THEIR data (the SAR basis) without ever holding content; deterministic. GDPR accountability (Art 5(2)) made provable.
  'audit-http-smoke.js',   // the ACCOUNTABILITY LAYER (HTTP): a leader reading beliefs about people is recorded content-free; a person exercises a Subject Access Request (Art 15) and receives everything held about them PLUS the trail of who accessed it — self only (another member's request never returns it); an admin reviews the org log and verifies the hash chain; the log is gated (a member is refused); tampering with the stored trail is detected. Erasure (Art 17) is itself recorded.
  'lifecycle-smoke.js',    // evidence lifecycle / knowledge governance (pure): what to keep vs let go — category half-lives, authority-modulated confidence decay, superseded→retire, redundancy merge, stale→proactive "still current?" inquiry
  'inquiry-http-smoke.js', // AUTONOMOUS INQUIRY (HTTP): the system proactively ASKS its own governed question — an expired shared record surfaces a non-leading "still current?" confirm routed to its owner, while a merely-aging record stays QUIET (never-nag); leader-gated; a "not now" dismissal stands it down (cooldown) so it's never repeated. Knowledge going stale becomes a question the system asks, not a fact it quietly reasons off.
  'inquiry-smoke.js',      // the Inquiry / epistemic-planning layer (recommendation-only): questions are actions — value-gate, critic, health-guard, least-burdensome routing, non-leading phrasing; derives uncertainties only from admissible evidence (private never enters)
  'member-methods-scan.js', // member-view guard: every called MemberApp._method is defined (catches called-but-undefined, e.g. a leader-only render branch invoking a missing helper that member-based boot tests never hit)
  'deadcode-scan.js',      // dead-code guard: fails on any unreferenced function (named or module-level arrow) across server.js + every js/ module — keeps retired-surface debt from re-accumulating
  // The unified attention pipeline (Codex layers, reviewed + integrated): engines discover →
  // feed normalises → packet scopes → priority office ranks. Pure modules, each self-tested;
  // the fixed suppression bug (a .map(_s) index leak) is covered here.
  'outcome-intelligence-smoke.js',       // the learning loop WITHOUT prediction (pure): summarises recorded action→outcome history per pattern×intervention with cautious limitations (not_causal/small_sample); never predicts, diagnoses, or claims causation
  'process-observations-smoke.js',       // the PROCESS-OBSERVATION deriver (pure): recorded action→outcome recurrence (via outcome-intelligence.summarize) becomes STRUCTURAL process signals — a way of working that reliably helps (protect) or repeatedly doesn't land (lighten) — aggregate (≥minCases), never a person (no subjectId, assertStructural), never-nag on a mixed picture; composes with outcome-intelligence in and process-reflection out
  'process-observations-http-smoke.js',  // process observations WIRED (HTTP): a team's recorded intervention outcomes surface in the unified packet as a method question ("the way the team responds to X keeps not landing"), grounded + aggregate + never naming the person in the raw records
  'process-reflection-smoke.js',         // process reflection (pure): challenges/protects METHODS not people ("what is this handoff protecting?"); handles friction AND strength; confirmation-gated, safe-text guarded, suppression before ranking
  'priority-office-smoke.js',            // the ranker (pure): decides which already-safe items lead; ask-first before changing a lead view; every suggestion confirmation-gated; suppression removes items before ranking; deterministic
  'intelligence-feed-smoke.js',          // the unified feed (pure): normalises artifacts from six engines (reasoner/proactive/outcome/process/self-model/playbook) into one safe feed; suppression before ranking; deterministic
  'scoped-intelligence-packet-smoke.js', // the scoping layer (pure): applies the org web to the feed — leader sees their subtree, member sees self+parent, no sibling leak; a good question travels upward as a safe artifact without granting the asker broader info
  'intelligence-packet-http-smoke.js',   // the pipeline WIRED (HTTP): GET /api/intelligence/packet gathers every engine's output through feed → scope → rank and returns ONE scoped, ranked read with a single lead; leak-safe across branches; every suggestion proposal-gated; degrades to a calm empty packet
  'connector-harness.js',  // the Connector SDK: identity/confidence + mapping contracts
  'google-provider-smoke.js', // the GOOGLE provider normaliser (pure): the first real provider behind the SDK turns raw Google Calendar/Gmail API JSON into the SDK's [{date}] shape while holding data-minimisation by construction — the INSIGHT tier emits ONLY a date (no title/body/location), Gmail is counted from metadata, all-day + timed events resolve, cancelled dropped, the ASSIST tier carries fuller detail as a separate private tier, scopes are least-privilege read-only, deterministic
  'google-connector-http-smoke.js', // the GOOGLE connector (HTTP): a person connects calendar/inbox (consent-gated), a raw Google API payload is pulled and MINIMISED to numbers-only before it reaches the kernel (a sensitive event title + email subject never cross), consent + connection are enforced, a source Google can't feed is refused, and an org in NO-EGRESS mode refuses the external pull outright
  'frontend-smoke.js',     // REAL headless-Chromium boot: every route + refresh + Support view; fails on any uncaught JS/parse error (self-skips if no Chromium). This is the guard that would have caught the mobile "Unexpected token" boot crash.
  'endpoint-smoke.js',   // boots the real app in-process (DB_OPTIONAL) — HTTP authz + Me context
];
for (const s of SUITES) {
  step(`suite — ${s}`, () => {
    const out = execFileSync('node', [path.join(__dirname, s)], { encoding: 'utf8' });
    process.stdout.write(out.replace(/^/gm, '  '));
  });
}

console.log(failed
  ? `\n════════\n✗ TRUTH LAYER RED — ${failed} step(s) failed. Do not merge.\n`
  : `\n════════\n✓ TRUTH LAYER GREEN — all sources parse, all suites pass.\n`);
process.exit(failed ? 1 : 0);
